config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'withdraw'
      patch 'withdraw'
      get 'unsubscribe'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum is_active: { 有効: true, 退会: false }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy

         enum sex: { man: 0, woman: 1}
         attachment :image

         validates :name, presence: true, uniqueness: true

         def active_for_authentication?
           super && (self.is_active == "有効")
         end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_user
    @user = User.find_by(name: params[:user][:name])
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_active
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def unsubscribe
  end

  def withdraw
    @user = current_user
    if @user.update(is_active: "退会")
      reset_session
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :email, :sex)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="profile-update col-lg12 col-md12 col-12">
      <h2 class="edit-title">プロフィール編集</h2>
        <%= form_with model:@user, local:true do |f| %>
        <div class="edit-box">
          <label for="inputImage">プロフィール画像</label>
          <%= f.file_field :image %>
        </div>
        <div class="edit-box">
          <label for="inputName">ユーザーネーム</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
        </div>
        <div class="edit-box">
          <label for="inputEmail">メールアドレス</label>
          <%= f.email_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス"%>
        </div>
        <div class="edit-box">
          <label for="inputSex">性別</label>
          <%= f.label :"男性"  %>
          <%= f.radio_button :sex, :man %>
          <%= f.label :"女性"  %>
          <%= f.radio_button :sex, :woman %>
        </div>
        <div class="edit-box">
          <%= f.submit "変更を保存", class: "glyphicon glyphicon-pencil btn btn-success pull-right" %>
          <% end %>
        </div>
        <div class="edit-box">
          <%= link_to "退会する", unsubscribe_users_path, class: "glyphicon glyphicon-tint btn btn-danger"%>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="profile col-lg12 col-md12 col-12">
      <%= attachment_image_tag @user, :image, fallback: "no_image.jpg", style: "height: 200px" %>
      <div>
        <p class="profile-text">ユーザーネーム:       <%= @user.name %></p>
      </div>
      <div>
        <p class="profile-text">性別:       <%= @user.sex_i18n %></p>
      </div>
      <div>
        <% if @user.id == current_user.id %>
        <p class="profile-text"><%= link_to "編集する", edit_user_path(@user), class: "glyphicon glyphicon-pencil btn btn-success pull-right" %></p>
        <% end %>
      </div>
    </div>
  </div>
    <div class="col-lg-12 col-md12 col-12">
      <h1>過去の投稿</h1>
      <div class="post-wrap">
        <% @posts.each do |postall| %>
          <div class="post-box">
            <p class="post-title"><%= postall.title %></p>
            <%= link_to post_path(postall.id) do %>
            <%= attachment_image_tag postall, :image, class:'post-thum' %>
            <% end %>
            <p class="user-name">ユーザーネーム   <%= postall.user.name %></p>
            <p class="post-review"><%= postall.review.truncate(30)  %></p>
          </div>
          <% end %>
          <%= paginate @posts %>
        </div>
    </div>

</div>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="user-destroy col-lg-12 col-md-12 col-12">
      <h2 class="destroy-text"><strong>本当に退会しますか？</strong></h2>
      <div class="destroy-button">
        <%= link_to "退会しない", user_path(current_user), class: "glyphicon glyphicon-home btn btn-primary" %>
        <%= link_to "退会する", withdraw_users_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: "glyphicon glyphicon-tint btn btn-danger" %>
      </div>
    </div>
  </div>
</div>