config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'withdraw'
      patch 'withdraw'
      get 'unsubscribe'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  validates :title, presence: true
  validates :review, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    self.favorites.where(user_id: user.id).exists?
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all.page(params[:page]).per(10)
    @random = Post.limit(3)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
    @post_comments = @post.post_comments
    #binding.irb
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  private
  def post_params
    params.require(:post).permit(:title, :rate_easy, :rate_smell, :rate_price, :rate_time, :image, :review)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> 件のエラーが発生しました</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <%= render 'posts/error', model: @post %>
  <% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
  <% end %>
  <div class-"row">
    <div class="post-edit-box col-lg12 col-md12 col-12">
      <h1 class="new-title">投稿編集</h1>
      <%= form_with model: @post, local:true do |f| %>
      <div>
        <h4 class="new-box">投稿画像</h4><%= f.attachment_field :image %>
      </div>
      <div class="review_star">
        <div class="review" id="star1">
          <h4 class="new-box">評価</h4>
          <%= f.label :rate_smell,'香り', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_smell, id: :review_star1 %>
          <script>
          $('#star1').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_smell]',
            half: true,
          });
          </script>
        </div>
        <div class="review" id="star2">
          <%= f.label :rate_time,'持続性', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_time, id: :review_star2 %>
          <script>
          $('#star2').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_time]',
            half: true,
          });
          </script>
        </div>
        <div class="review" id="star3">
          <%= f.label :rate_price,'価格', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_price, id: :review_star3 %>
          <script>
          $('#star3').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_price]',
            half: true,
          });
          </script>
        </div>
        <div class="review" id="star4">
          <%= f.label :rate_easy,'使いやすさ', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_easy, id: :review_star4 %>
          <script>
          $('#star4').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_easy]',
            half: true,
          });
          </script>
        </div>
      </div>
      <div>
        <h4 class="new-box">タイトル</h4>
        <%= f.text_field :title , size: "5x3", class: "form-control"  %>
      </div>
       <div>
         <h4 class="new-box">レビュー</h4>
         <%= f.text_area :review , size: "10x5", class: "form-control" %>
       </div>
       <% if @post.user == current_user %>
       <div class="edit-box">
          <%= f.submit "変更を保存", class: "glyphicon glyphicon-pencil btn btn-success pull-right" %>
          <% end %>
        </div>
        <div class="edit-box">
          <%= link_to "削除する", post_path(@post), method: :delete, class: "glyphicon glyphicon-tint btn btn-danger"%>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
 <div class="container">
   <div class-"post-all">
    <div class="row">
      <div class="sidebar col-lg-3 col-md-3 col-3">
        <h2 class="post-title-side">おすすめ投稿</h1>
        <% @random.each do |postrandom| %>
        <% next if postrandom.user.is_active == "退会" %>
        <div class="post-box-side">
          <p class="post-title"><%= postrandom.title %></p>
          <%= link_to post_path(postrandom.id) do %>
          <%= attachment_image_tag postrandom, :image, class:'post-thum' %>
          <% end %>
          <p class="user-name">ユーザーネーム   <%= postrandom.user.name %></p>
          <p class="post-review"><%= postrandom.review %></p>
        </div>
        <% end %>
      </div>
      <div class="mainbar col-lg-9 col-md-9 col-9">
        <h2 class="post-title-main">投稿一覧</h1>
        <div class="post-wrap">
          <% @posts.each do |postall| %>
          <% next if postall.user.is_active == "退会" %>
          <div class="post-box-main">
            <p class="post-title"><%= postall.title %></p>
            <%= link_to post_path(postall.id) do %>
            <%= attachment_image_tag postall, :image, class:'post-thum' %>
            <% end %>
            <p class="user-name">ユーザーネーム   <%= postall.user.name %></p>
            <p class="post-review"><%= postall.review.truncate(30) %></p>
          </div>
          <% end %>
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= render 'posts/error', model: @post %>
  <div class-"row">
    <div class="post-new-box col-lg12 col-md12 col-12">
      <h1 class="new-title">新規投稿</h1>
      <%= form_with model: @post, local:true do |f| %>
      <div>
        <h4 class="new-box">投稿画像</h4><%= f.attachment_field :image %>
      </div>
      <div class="review_star">
        <div class="review" id="star1">
          <h4 class="new-box">評価</h4>
          <%= f.label :rate_smell,'香り', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_smell, id: :review_star1 %>
          <script>
          $('#star1').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_smell]',
            half: true,
          });
          </script>
        </div>
        <div class="review" id="star2">
          <%= f.label :rate_time,'持続性', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_time, id: :review_star2 %>
          <script>
          $('#star2').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_time]',
            half: true,
          });
          </script>
        </div>
        <div class="review" id="star3">
          <%= f.label :rate_price,'価格', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_price, id: :review_star3 %>
          <script>
          $('#star3').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_price]',
            half: true,
          });
          </script>
        </div>
        <div class="review" id="star4">
          <%= f.label :rate_easy,'使いやすさ', class:'col-md-2 col-form-label' %>
          <%= f.hidden_field :rate_easy, id: :review_star4 %>
          <script>
          $('#star4').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate_easy]',
            half: true,
          });
          </script>
        </div>
      </div>
      <div>
        <h4 class="new-box">タイトル</h4>
        <%= f.text_field :title , size: "5x3", class: "form-control"  %>
      </div>
       <div>
         <h4 class="new-box">レビュー</h4>
         <%= f.text_area :review , size: "10x5", class: "form-control" %>
       </div>
       <div>
         <%= f.submit '新規投稿' %>
         <% end %>
       </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post-detail">
    <div class="row">
      <div class="post-detail-box col-lg-4 col-md-4 col-4">
        <div>
          <p class="profile-detail">ユーザーネーム:       <%= @user.name %></p>
        </div>
        <div>
        　<p class="profile-detail">性別:       <%= @user.sex_i18n %></p>
        </div>
        <div class="profile-detail">
          <%= attachment_image_tag @post, :image, width: '200' %>
        </div>
        <div class="star-rate-box">
          <div id="star-rate-smell<%= @post.id %>">
            <p class="star-label">香り</p>
          </div>
          <script>
          $('#star-rate-smell<%= @post.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @post.rate_smell %>,
          });
          </script>
        </div>
        <div class="star-rate-box">
          <div id="star-rate-time<%= @post.id %>">
            <p class="star-label">持続性</p>
          </div>
          <script>
          $('#star-rate-time<%= @post.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @post.rate_time %>,
          });
          </script>
        </div>
        <div class="star-rate-box">
          <div id="star-rate-price<%= @post.id %>">
            <p class="star-label">価格</p>
          </div>
          <script>
          $('#star-rate-price<%= @post.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @post.rate_price %>,
          });
          </script>
        </div>
        <div class="star-rate-box">
          <div id="star-rate-easy<%= @post.id %>">
            <p class="star-label">使いやすさ</p>
          </div>
          <script>
          $('#star-rate-easy<%= @post.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @post.rate_easy %>,
          });
          </script>
        </div>
      </div>
      <div class="chart col-lg-8 col-md-8 col-8">
        <div style="position: relative; top: 200px; width: 100%; height: 100%;">
          <canvas id="myChart"></canvas>
          <script>
          var ctx = document.getElementById("myChart");
          var myChart = new Chart(ctx, {
            type: 'radar',
            data: {
              labels: ["香り", "持続性", "価格", "使いやすさ"],
              datasets:
              [
                {
                  label: '<%= @post.title %>',
                  backgroundColor: 'rgba(255,192,203,0.2)',
                  borderColor: 'rgba(255,192,203,0.2)',
                  borderColor: 'rgba(255,192,203)',
                  data: [<%= @post.rate_smell %>, <%= @post.rate_time %>, <%= @post.rate_time %>, <%= @post.rate_easy %>]
                },
              ]
            },
            options: {
              scale: {
                pointLabels: {
                  fontSize: 20,
                },
                ticks: {
                  suggestedMin: 0,
                  suggestedMax: 5,
                  fontSize: 20,
                }
              },
              legend: {
                display: false
              }
            }
          });
          </script>
        </div>
      </div>
    </div>
      <div class="review-detail col-lg-11 col-md-11 col-11">
        <p class="review-text"><%= @post.review %></p>
        <p class="review-detail-bottom"><%= @post.created_at.strftime('%Y/%m/%d') %></p>
        <div class="review-detail-bottom">
          <% if user_signed_in? %>
          <div id="favorites_buttons_<%= @post.id %>">
            <%= render "favorites/favorite", post: @post %>
          </div>
          <% end %>
        </div>
        <% if @post.user == current_user %>
        <div class="review-detail-bottom">
          <%= link_to "編集する", edit_post_path(@post), class: "glyphicon glyphicon-pencil btn btn-success pull-right" %>
          <%= link_to "削除する", post_path(@post), method: :delete, data: {confirm: "削除しますか？"}, class: "glyphicon glyphicon-tint btn btn-danger" %>
        </div>
        <% end %>
      </div>
    </div>
    <%= render 'posts/error', model: @post_comment %>
    <% if user_signed_in? %>
    <div class="review-box col-lg-12 col-m12 col12">
      <%= form_with(model:[@post, @post_comment], local: true) do |f| %>
      <div class="comment-form">
      <%= f.text_area :comment, placeholder: "コメントをここに", size: "10x5", class: "form-control" %>
      </div>
      <div>
        <%= f.submit "送信する" %>
      </div>
      <% end %>
    </div>
    <div class="user-comment">
      <p class="comment-count">コメント件数：<%= @post.post_comments.count %></p>
      <div class="comment-box">
        <% @post.post_comments.each do |post_comment| %>
        <p class="comment_user">ユーザーネーム:     <%= post_comment.user.name %></p>
        <p class="comment_user">コメント:     <%= post_comment.comment %></p>
        <p class="comment_user"><%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
        <% if post_comment.user == current_user %>
        <div>
          <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), data: {confirm: '本当に削除しますか？'}, method: :delete, class: "glyphicon glyphicon-tint btn btn-danger" %>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>